### ISSUE TITLE
protobuf error in running pipeline

### ISSUE THREAD

**Issue by ryandawsonuk** [ThoughtWorksInc/CD4ML-Scenarios#23]
Today when I run the pipeline in Jenkins I get this error:

```

[2022-05-26T11:09:07.506Z] Traceback (most recent call last):

[2022-05-26T11:09:07.506Z]   File "/var/jenkins_home/workspace/CD4ML-Scenarios_master/run_python_script.py", line 50, in <module>

[2022-05-26T11:09:07.506Z]     run_python_script(script, arguments, profiler=profiler)

[2022-05-26T11:09:07.506Z]   File "/var/jenkins_home/workspace/CD4ML-Scenarios_master/run_python_script.py", line 26, in run_python_script

[2022-05-26T11:09:07.506Z]     from scripts import register_model as executable_script

[2022-05-26T11:09:07.506Z]   File "/var/jenkins_home/workspace/CD4ML-Scenarios_master/scripts/register_model.py", line 3, in <module>

[2022-05-26T11:09:07.506Z]     from cd4ml.register_model import register_model

[2022-05-26T11:09:07.506Z]   File "/var/jenkins_home/workspace/CD4ML-Scenarios_master/cd4ml/register_model.py", line 4, in <module>

[2022-05-26T11:09:07.506Z]     import mlflow

[2022-05-26T11:09:07.506Z]   File "/usr/local/lib/python3.9/dist-packages/mlflow/__init__.py", line 34, in <module>

[2022-05-26T11:09:07.506Z]     import mlflow.tracking._model_registry.fluent

[2022-05-26T11:09:07.506Z]   File "/usr/local/lib/python3.9/dist-packages/mlflow/tracking/__init__.py", line 8, in <module>

[2022-05-26T11:09:07.506Z]     from mlflow.tracking.client import MlflowClient

[2022-05-26T11:09:07.506Z]   File "/usr/local/lib/python3.9/dist-packages/mlflow/tracking/client.py", line 16, in <module>

[2022-05-26T11:09:07.506Z]     from mlflow.entities import Experiment, Run, RunInfo, Param, Metric, RunTag, FileInfo, ViewType

[2022-05-26T11:09:07.506Z]   File "/usr/local/lib/python3.9/dist-packages/mlflow/entities/__init__.py", line 6, in <module>

[2022-05-26T11:09:07.506Z]     from mlflow.entities.experiment import Experiment

[2022-05-26T11:09:07.506Z]   File "/usr/local/lib/python3.9/dist-packages/mlflow/entities/experiment.py", line 2, in <module>

[2022-05-26T11:09:07.506Z]     from mlflow.entities.experiment_tag import ExperimentTag

[2022-05-26T11:09:07.506Z]   File "/usr/local/lib/python3.9/dist-packages/mlflow/entities/experiment_tag.py", line 2, in <module>

[2022-05-26T11:09:07.506Z]     from mlflow.protos.service_pb2 import ExperimentTag as ProtoExperimentTag

[2022-05-26T11:09:07.506Z]   File "/usr/local/lib/python3.9/dist-packages/mlflow/protos/service_pb2.py", line 18, in <module>

[2022-05-26T11:09:07.506Z]     from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2

[2022-05-26T11:09:07.506Z]   File "/usr/local/lib/python3.9/dist-packages/mlflow/protos/scalapb/scalapb_pb2.py", line 29, in <module>

[2022-05-26T11:09:07.506Z]     options = _descriptor.FieldDescriptor(

[2022-05-26T11:09:07.506Z]   File "/usr/local/lib/python3.9/dist-packages/google/protobuf/descriptor.py", line 560, in __new__

[2022-05-26T11:09:07.506Z]     _message.Message._CheckCalledFromGeneratedFile()

[2022-05-26T11:09:07.506Z] TypeError: Descriptors cannot not be created directly.
```

But it was working for me yesterday.

There were commits yesterday and also I am now using rancher desktop but I suspect this is about pinning versions just like https://github.com/databrickslabs/dbx/issues/257 for which the solution is https://github.com/databrickslabs/dbx/pull/256/commits/bf56196c549d90436128a1a04444c05709ea2f8e

**Comment by ryandawsonuk** [comment]
The [protobuf release which caused this](https://pypi.org/project/protobuf/#history) has now been yanked:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/22754674/170687117-e784200e-b9d0-4048-a945-abe80bb6b9e9.png">

So the problem will now have disappeared. But we should pin version anyway.
